name: CI
on:
  push:
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy files to special folder
        run: mkdir -p 3dweb-print-studio && cp -a wp-content/plugins/3dweb-print-studio/* 3dweb-print-studio

      # Create zip file
      - name: Create zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r 3dweb-print-studio.zip 3dweb-print-studio

      # Enter new working dir
      - name: enter work dir
        run: cd 3dweb-print-studio

      # Deploy to Wordpress
      - name: WordPress Plugin Deploy
        id: deploy
        uses: ./.github/actions/wp-deploy
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG : 3dweb-print-studio
          ASSETS_DIR : plugin-assets

